version: "3.9"
services:
  rabbitmq:
		hostname: rabbitmq
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_User}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_Pass}
    ports:
      - ${RABBIT_ManagementPort}:15672
      - ${RABBIT_MainPort}:5672
    networks:
      - bridge-net
      
test:
    hostname: testapi
    container_name: testapi
    build:
      context: /docker/testapi
      dockerfile: Dockerfile
    ports:
      - ${Test_Port}:1234
    networks:
      - bridge-net
    depends_on:
      - rabbitmq

networks:
  bridge-net:
    name: bridge_network
    driver: bridge