version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5003:5003" #Backend API Port
      - "5500:5500" #Frontend Port
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: ["flask", "run","--host=0.0.0.0"]